### ISSUE TITLE
Upstream changes or rebase on upstream

### ISSUE THREAD

**Issue by tonytanger** [remohammadi/gorm#2]
Any plans to upstream these changes? Gorm 2.0 looks like a long way to go.

If not, could this fork be updated occasionally with changes from upstream?

Thanks.

**Comment by remohammadi** [comment]
Done!

[`v1.9.1+context`](https://github.com/remohammadi/gorm/releases/tag/v1.9.1%2Bcontext) is the changes made on the jinzhu's `v1.9.1` release, and `master` is updated to be the changes on the current `master` of jinzhu's gorm.
